from pathlib import Path
from html import escape
root=Path('/mnt/data/tamperesiivous-site')
DOMAIN='https://tamperesiivous.com'
PHONE='+358 44 931 8824'
PHONE_LINK='+358449318824'
EMAIL='info@tamperesiivous.com'
BID='3549202-5'

nav='''<nav class="nav"><div class="container"><a class="logo" href="/">Tampere<span>Siivous</span></a><div class="navlinks"><a href="/toimistosiivous/">Toimistosiivous</a><a href="/yrityssiivous/">Yrityssiivous</a><a href="/palvelut/">Palvelut</a><a href="/hinnasto/">Hinnasto</a><a href="/yritys/">Yritys</a><a href="/ota-yhteytta/">Yhteys</a><a class="btn primary" href="/pyyda-tarjous/">Pyydä tarjous</a></div></div></nav>'''

def topbar(): return f'''<div class="topbar"><div class="container"><span>Paikallinen siivouspalvelu yrityksille Tampereella ja Pirkanmaalla</span><span><a href="tel:{PHONE_LINK}">{PHONE}</a> &nbsp; • &nbsp; <a href="mailto:{EMAIL}">{EMAIL}</a></span></div></div>'''

def footer(): return f'''<footer class="footer"><div class="container"><div class="footergrid"><div><h3>TampereSiivous</h3><p>Toimistojen, yritysten ja toimitilojen luotettava siivouskumppani Tampereella ja Pirkanmaalla. Selkeä palvelu, joustava aikataulu ja siisti lopputulos.</p><p><strong>{PHONE}</strong><br>{EMAIL}<br>Y-tunnus {BID}</p></div><div><h4>Yrityksille</h4><a href="/toimistosiivous/">Toimistosiivous</a><a href="/yrityssiivous/">Yrityssiivous</a><a href="/sopimussiivous/">Sopimussiivous</a><a href="/toimitilasiivous/">Toimitilasiivous</a><a href="/liiketilasiivous/">Liiketilasiivous</a><a href="/porrassiivous/">Porrassiivous</a></div><div><h4>Lisäpalvelut</h4><a href="/ikkunanpesu/">Ikkunanpesu</a><a href="/muuttosiivous/">Muuttosiivous</a><a href="/erikoissiivous/">Erikoissiivous</a><a href="/rakennussiivous/">Rakennussiivous</a><a href="/alueet/">Palvelualueet</a><a href="/ota-yhteytta/">Ota yhteyttä</a></div></div><small>© 2026 TampereSiivous. Kaikki oikeudet pidätetään. &nbsp; <a style="display:inline" href="/tietosuoja/">Tietosuojaseloste</a> · <a style="display:inline" href="/saavutettavuus/">Saavutettavuus</a></small></div></footer><div class="mobile-cta"><a href="tel:{PHONE_LINK}">Soita</a><a class="green" href="/pyyda-tarjous/">Tarjous</a></div>'''

def schema(name,desc,url,faq=None):
    import json
    data={"@context":"https://schema.org","@type":["LocalBusiness","CleaningService"],"name":"TampereSiivous","url":DOMAIN,"telephone":PHONE,"email":EMAIL,"description":desc,"areaServed":["Tampere","Pirkkala","Nokia","Ylöjärvi","Kangasala","Lempäälä"],"address":{"@type":"PostalAddress","addressLocality":"Tampere","addressRegion":"Pirkanmaa","addressCountry":"FI"},"priceRange":"€€"}
    out=[data]
    if faq:
        out.append({"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":q,"acceptedAnswer":{"@type":"Answer","text":a}} for q,a in faq]})
    return ''.join('<script type="application/ld+json">'+json.dumps(d,ensure_ascii=False)+'</script>' for d in out)

def page(title,desc,path,body,faq=None,ogtitle=None):
    canonical=DOMAIN+('/' if path=='' else '/'+path.strip('/')+'/')
    return f'''<!doctype html><html lang="fi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)}</title><meta name="description" content="{escape(desc)}"><link rel="canonical" href="{canonical}"><meta name="robots" content="index,follow,max-image-preview:large"><meta property="og:type" content="website"><meta property="og:locale" content="fi_FI"><meta property="og:title" content="{escape(ogtitle or title)}"><meta property="og:description" content="{escape(desc)}"><meta property="og:url" content="{canonical}"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="/assets/styles.css">{schema(title,desc,canonical,faq)}</head><body>{topbar()}{nav}{body}{footer()}<script src="/assets/site.js" defer></script></body></html>'''

def hero(h1,lead,crumb='Etusivu',eyebrow='Siivouspalvelu Tampere'):
    return f'''<header class="pagehero"><div class="container"><div class="breadcrumbs"><a href="/">Etusivu</a> / {escape(crumb)}</div><span class="eyebrow">{escape(eyebrow)}</span><h1>{h1}</h1><p>{lead}</p><div class="actions"><a class="btn primary" href="/pyyda-tarjous/">Pyydä maksuton tarjous</a><a class="btn ghost" href="tel:{PHONE_LINK}">Soita {PHONE}</a></div></div></header>'''

def faq_html(items): return '<section class="band"><div class="container"><div class="section-head"><h2>Usein kysyttyä</h2></div><div class="faq">'+''.join(f'<div class="faq-item"><h3>{q}</h3><p>{a}</p></div>' for q,a in items)+'</div></div></section>'

def service_body(h1,lead,crumb,intro,features,includes,faq,keywords=''):
    cards=''.join(f'<div class="feature"><h3>{h}</h3><p>{p}</p></div>' for h,p in features)
    checks=''.join(f'<div class="check"><b>✓</b><span>{x}</span></div>' for x in includes)
    return hero(h1,lead,crumb,keywords or 'Yrityssiivous Tampere')+f'''<main><section><div class="container split"><div class="content">{intro}</div><div class="price-card"><span class="eyebrow">Helppo aloittaa</span><h2>Maksuton kartoitus</h2><p>Kerro tilan koko, käyttötarkoitus ja toivottu siivousrytmi. Teemme selkeän ehdotuksen ilman piilokuluja.</p><a class="btn primary" href="/pyyda-tarjous/">Pyydä tarjous</a></div></div></section><section class="band"><div class="container"><div class="section-head"><h2>Miksi TampereSiivous?</h2><p>Yrityssiivous suunnitellaan tilan käytön mukaan, ei valmiin geneerisen listan perusteella.</p></div><div class="grid">{cards}</div></div></section><section><div class="container split"><div><div class="section-head"><h2>Mitä siivoukseen voidaan sisällyttää?</h2></div><div class="checklist">{checks}</div></div><div class="cta"><h2>Säännöllinen siivous ilman säätöä</h2><p>Sovitaan tehtävät, laatutaso ja aikataulu. Me huolehdimme, että työympäristö pysyy siistinä myös kiireisen arjen keskellä.</p><a class="btn primary" href="/ota-yhteytta/">Kysy lisää</a></div></div></section>{faq_html(faq)}</main>'''

pages={}
# Home
home_faq=[('Mitä toimistosiivous Tampereella maksaa?','Hinta riippuu tilan koosta, siivoustiheydestä, käyttöasteesta ja sovituista tehtävistä. Säännöllinen sopimussiivous hinnoitellaan yleensä kohdekohtaisesti maksuttoman kartoituksen jälkeen.'),('Voiko siivouksen tehdä ennen työpäivää tai sen jälkeen?','Kyllä. Toimistosiivous voidaan ajoittaa aamuun, iltaan tai muuhun yrityksen toimintaan sopivaan aikaan.'),('Palveletteko Tampereen ulkopuolella?','Kyllä. Palvelemme Tampereen lisäksi muun muassa Pirkkalassa, Nokialla, Ylöjärvellä, Kangasalla ja Lempäälässä.')]
home_body=f'''<header class="hero"><div class="container"><div><span class="eyebrow">Toimistosiivous Tampere & Pirkanmaa</span><h1>Puhdas toimisto. Parempi työpäivä.</h1><p>TampereSiivous tarjoaa joustavaa toimisto- ja yrityssiivousta Tampereella. Säännöllinen sopimussiivous, kertasiivoukset ja lisäpalvelut yhdeltä paikalliselta kumppanilta.</p><div class="actions"><a class="btn primary" href="/pyyda-tarjous/">Pyydä tarjous</a><a class="btn ghost" href="/toimistosiivous/">Tutustu toimistosiivoukseen</a></div><div class="trustrow"><span>✓ Paikallinen palvelu</span><span>✓ Yrityksille räätälöity</span><span>✓ Joustavat ajat</span><span>✓ Selkeä hinnoittelu</span></div></div><div class="visual"><div class="card big"><span class="eyebrow">Yrityksille</span><div class="sparkles">✦</div><h3>Siisteys, jonka huomaa.</h3><p>Työpisteet, neuvottelutilat, keittiöt, wc-tilat, lattiat ja yhteiset tilat sovitun palvelusuunnitelman mukaan.</p></div><div class="card metric"><strong>1–7×</strong><span>viikossa tai tarpeen mukaan</span></div><div class="card quote"><b>Helppo tarjouspyyntö</b><p>Vastaa muutamaan kysymykseen ja saat kohteellesi sopivan ehdotuksen.</p></div></div></div></header><main><section><div class="container"><div class="section-head"><span class="eyebrow">Palvelut yrityksille</span><h2>Siivouspalvelut työpaikoille Tampereella</h2><p>Rakensimme palveluvalikoiman erityisesti toimistoille, liiketiloille, taloyhtiöille ja muille toimitiloille.</p></div><div class="grid">''' + ''.join([
'<a class="service-card" href="/toimistosiivous/"><div class="icon">⌂</div><h3>Toimistosiivous</h3><p>Säännöllinen ja huolellinen toimistojen ylläpitosiivous.</p><span class="more">Lue lisää →</span></a>',
'<a class="service-card" href="/sopimussiivous/"><div class="icon">↻</div><h3>Sopimussiivous</h3><p>Vakioitu siivousrytmi ja kohdekohtainen palvelusuunnitelma.</p><span class="more">Lue lisää →</span></a>',
'<a class="service-card" href="/toimitilasiivous/"><div class="icon">▦</div><h3>Toimitilasiivous</h3><p>Toimistot, työtilat, varastot, studiot ja yhteiset tilat.</p><span class="more">Lue lisää →</span></a>',
'<a class="service-card" href="/liiketilasiivous/"><div class="icon">◇</div><h3>Liiketilasiivous</h3><p>Asiakas- ja myymälätilojen siisteys ennen, aikana tai jälkeen aukiolon.</p><span class="more">Lue lisää →</span></a>',
'<a class="service-card" href="/porrassiivous/"><div class="icon">▤</div><h3>Porrassiivous</h3><p>Taloyhtiöiden ja kiinteistöjen rappujen sekä yhteistilojen puhtaanapito.</p><span class="more">Lue lisää →</span></a>',
'<a class="service-card" href="/erikoissiivous/"><div class="icon">✦</div><h3>Erikoissiivous</h3><p>Ikkunat, lattioiden peruspesut, tekstiilipinnat ja tehostetut siivoukset.</p><span class="more">Lue lisää →</span></a>'
]) + '''</div></div></section><section class="band"><div class="container split"><div><span class="eyebrow">Toimistosiivouksen asiantuntija</span><h2>Siivous mukautuu työpaikkaanne</h2><p>Toimiston siivoustarve muuttuu henkilöstömäärän, käyttöasteen, viikonpäivän ja tilatyypin mukaan. Siksi määrittelemme yhdessä siivottavat alueet, tehtävälistan ja rytmin.</p><div class="checklist"><div class="check"><b>✓</b><span>Työpisteet ja yhteiset tilat</span></div><div class="check"><b>✓</b><span>Keittiö, taukotilat ja wc-tilat</span></div><div class="check"><b>✓</b><span>Lattiat, kosketuspinnat ja roskahuolto</span></div><div class="check"><b>✓</b><span>Lisäpalvelut tarpeen mukaan</span></div></div></div><div class="stats"><div class="stat"><strong>6</strong><span>keskeistä yrityspalvelua</span></div><div class="stat"><strong>1–7×</strong><span>siivousrytmi viikossa</span></div><div class="stat"><strong>100%</strong><span>kohdekohtainen suunnitelma</span></div><div class="stat"><strong>0€</strong><span>tarjouspyyntö</span></div></div></div></section><section><div class="container"><div class="section-head"><h2>Palvelualue Tampereella ja lähikunnissa</h2><p>Siivouspalvelut yrityksille Tampereen keskustasta Hervantaan, Hatanpäälle, Nekalaan, Lielahteen ja lähikuntiin.</p></div><div class="areas">'''+''.join(f'<span class="pill">{a}</span>' for a in ['Tampere keskusta','Hervanta','Hatanpää','Nekala','Lielahti','Kaleva','Tammela','Pirkkala','Nokia','Ylöjärvi','Kangasala','Lempäälä'])+'''</div></div></section><section><div class="container"><div class="cta"><span class="eyebrow">Tarjous yritykselle</span><h2>Haluatko siivouksesta yhden asian vähemmän hoidettavaksi?</h2><p>Kerro kohteesta. Saat ehdotuksen toimisto- tai yrityssiivouksen sisällöstä, rytmistä ja hinnasta.</p><div class="actions"><a class="btn primary" href="/pyyda-tarjous/">Pyydä tarjous</a><a class="btn ghost" style="background:#fff" href="tel:'''+PHONE_LINK+'''">Soita meille</a></div></div></div></section>'''+faq_html(home_faq)+'''</main>'''
pages['index.html']=page('Toimistosiivous Tampere | Yrityssiivous | TampereSiivous','Toimistosiivous ja yrityssiivous Tampereella. Joustava sopimussiivous toimistoille ja toimitiloille Tampereella ja Pirkanmaalla. Pyydä tarjous.','',home_body,home_faq)

services={
 'toimistosiivous':('Toimistosiivous Tampereella','Säännöllinen toimistosiivous pitää työympäristön siistinä, viihtyisänä ja valmiina työntekijöille sekä asiakkaille. Palvelemme pieniä ja suuria toimistoja Tampereella.','Toimistosiivous','<h2>Toimistosiivous, joka toimii työpäivän ehdoilla</h2><p>Hyvä toimistosiivous ei häiritse työntekoa. Se tapahtuu oikeaan aikaan, oikeilla menetelmillä ja juuri niissä tiloissa, joissa puhtautta eniten tarvitaan. TampereSiivous suunnittelee ylläpitosiivouksen toimiston koon, käyttöasteen ja toivotun laatutason mukaan.</p><p>Palvelu voi olla päivittäinen, muutaman kerran viikossa tai harvempi ylläpitosiivous. Tarvittaessa yhdistämme mukaan ikkunoiden pesun, lattioiden peruspesun ja muut kausittaiset työt.</p>', [('Sama selkeä palvelusuunnitelma','Sovitaan mitä tehdään jokaisella käynnillä ja mitä tehdään harvemmin.'),('Joustavat työajat','Aamu-, päivä- tai iltasiivous yrityksen toiminnan mukaan.'),('Toimistoon sopivat menetelmät','Huomioimme työpisteet, elektroniikan, neuvottelutilat ja paljon käytetyt kosketuspinnat.')], ['Työpisteiden vapaiden pintojen pyyhintä','Neuvottelu- ja yhteistilojen siivous','Keittiön ja taukotilojen puhdistus','WC-tilojen puhdistus ja tarvikkeiden täydennys sovittaessa','Lattioiden imurointi ja kosteapyyhintä','Roskakorien tyhjennys ja jätteiden lajittelun tuki','Ovien, kahvojen ja kosketuspintojen pyyhintä'], [('Kuinka usein toimisto kannattaa siivota?','Yleinen rytmi on 1–5 kertaa viikossa. Sopiva määrä riippuu henkilöstömäärästä, tilan käyttöasteesta, asiakasliikenteestä ja tilatyypeistä.'),('Voiko toimistosiivouksen tehdä iltaisin?','Kyllä. Siivous voidaan ajoittaa ennen työpäivää, sen jälkeen tai muuhun rauhalliseen ajankohtaan.'),('Sisältyvätkö välineet ja aineet palveluun?','Palvelun sisältö sovitaan tarjouksessa. Voimme toteuttaa kokonaisuuden omilla ammattikäyttöön sopivilla välineillä ja aineilla.')], 'Toimistosiivous Tampere'),
 'yrityssiivous':('Yrityssiivous Tampereella','Yrityssiivous Tampereella toimistoille, liiketiloille ja muille työympäristöille. Räätälöity palvelu, selkeä tarjous ja joustava siivousrytmi.','Yrityssiivous','<h2>Yrityssiivous eri kokoisiin tiloihin</h2><p>Yrityssiivous yhdistää ylläpitosiivouksen, tarvittavat lisätyöt ja ennakoitavan palvelurytmin. Tavoitteena on, että tilat näyttävät siisteiltä henkilöstölle, vieraille ja asiakkaille ilman että yrityksen täytyy johtaa siivousta itse.</p><p>Palvelu sopii muun muassa toimistoihin, studioihin, vastaanottotiloihin, myymälöihin, varastoihin ja pieniin tuotanto- tai työtiloihin.</p>', [('Kohdekohtainen toteutus','Siivous perustuu yrityksen tiloihin, käyttöön ja aukioloaikoihin.'),('Yksi kumppani','Ylläpitosiivous ja kausittaiset lisätyöt voidaan yhdistää samaan palveluun.'),('Skaalautuva palvelu','Siivousrytmiä voidaan muuttaa sesonkien ja käyttöasteen mukana.')], ['Toimisto- ja työtilat','Asiakas- ja vastaanottotilat','Sosiaalitilat ja henkilöstökeittiöt','Saniteettitilat','Lattiat ja sisäänkäynnit','Pölynhallinta ja kosketuspinnat','Kausittaiset tehosiivoukset'], [('Mitä yrityssiivous sisältää?','Sisältö määritellään kohteen mukaan. Tavallisesti siihen kuuluu lattioiden, tasojen, wc- ja taukotilojen sekä yhteisten tilojen säännöllinen puhdistus.'),('Miten yrityssiivous hinnoitellaan?','Hintaan vaikuttavat neliöt, tilatyypit, käyttöaste, siivoustiheys ja palvelun sisältö.'),('Voiko palveluun lisätä ikkunanpesun?','Kyllä. Ikkunanpesut ja monet muut erikoistyöt voidaan sopia erillisinä tai kausittaisina lisäpalveluina.')], 'Yrityssiivous Tampere'),
 'sopimussiivous':('Sopimussiivous Tampereella','Sopimussiivous yrityksille Tampereella. Vakioitu siivousrytmi, sovittu laatutaso ja joustava palvelu toimistoihin ja toimitiloihin.','Sopimussiivous','<h2>Säännöllinen sopimussiivous vähentää yllätyksiä</h2><p>Sopimussiivouksessa määritellään etukäteen tehtävät, siivousrytmi, ajankohta ja mahdolliset jaksotyöt. Se sopii yrityksille, jotka haluavat pitää tilat jatkuvasti siisteinä ilman erillisiä tilauksia.</p><p>Palvelusuunnitelmaa voidaan tarkistaa, jos henkilöstömäärä, tilankäyttö tai tarpeet muuttuvat.</p>', [('Ennakoitava','Tiedät mitä tehdään ja milloin.'),('Joustava','Palvelua voidaan kasvattaa tai keventää tilanteen mukaan.'),('Helppo hallita','Yksi sopimus voi kattaa ylläpidon ja sovitut kausityöt.')], ['Päivittäinen tai viikoittainen ylläpitosiivous','Saniteetti- ja taukotilojen hoito','Lattioiden ylläpito','Roskahuolto sovitusti','Kosketuspintojen puhdistus','Kausityöt ja tehosiivoukset','Laatutason tarkistaminen tarpeen mukaan'], [('Mikä on sopimussiivous?','Sopimussiivous on toistuva palvelu, jossa siivous tehdään sovitulla rytmillä ja sovitun työohjeen mukaisesti.'),('Onko sopimus pakko tehdä pitkäksi aikaa?','Sopimuksen kesto ja ehdot sovitaan tarjouksen yhteydessä yrityksen tarpeen mukaan.'),('Voiko siivoustiheyttä muuttaa myöhemmin?','Kyllä. Siivousrytmiä voidaan tarkistaa, jos tilojen käyttö muuttuu.')], 'Sopimussiivous Tampere'),
 'toimitilasiivous':('Toimitilasiivous Tampereella','Toimitilasiivous Tampereella toimistoihin, työtiloihin, varastoihin ja muihin yritystiloihin. Pyydä kohdekohtainen tarjous.','Toimitilasiivous','<h2>Toimitilasiivous tilan käyttötarkoituksen mukaan</h2><p>Kaikkia toimitiloja ei kannata siivota samalla tavalla. Asiakaspalvelutila, toimisto, varasto ja henkilöstön sosiaalitila vaativat erilaisen työjärjestyksen ja siivoustiheyden.</p><p>Rakennamme palvelun alueittain: mitä siivotaan jokaisella käynnillä, mitä viikoittain ja mitkä tehtävät hoidetaan jaksotöinä.</p>', [('Tilakohtainen työohje','Kohteen eri alueet voidaan siivota eri rytmillä.'),('Järkevä resursointi','Siivous kohdistetaan sinne, missä käyttö ja likaantuminen ovat suurimmat.'),('Lisäpalvelut','Ikkunat, lattiat ja muut erikoistyöt voidaan liittää palveluun.')], ['Toimistot ja neuvotteluhuoneet','Vastaanotto- ja aulatilat','Varastot ja kevyet työtilat','Pukuhuoneet ja sosiaalitilat','Keittiö- ja taukotilat','WC-tilat','Sisäänkäynnit ja kulkureitit'], [('Mihin toimitiloihin palvelu sopii?','Palvelu sopii esimerkiksi toimistoihin, varastoihin, studioihin, vastaanottoihin, pieniin työtiloihin ja erilaisiin yritysten yhteistiloihin.'),('Voidaanko eri tiloja siivota eri tiheydellä?','Kyllä. Tämä on usein kustannustehokkain tapa toteuttaa toimitilasiivous.'),('Palveletteko Pirkanmaalla?','Kyllä. Tampereen lisäksi palvelemme sovitusti lähikunnissa.')], 'Toimitilasiivous Tampere'),
 'liiketilasiivous':('Liiketilasiivous Tampereella','Liiketilasiivous Tampereella myymälöihin, showroomeihin ja asiakastiloihin. Siisti ensivaikutelma ja joustava toteutus.','Liiketilasiivous','<h2>Siisti liiketila tukee asiakaskokemusta</h2><p>Liiketilassa puhtaus näkyy heti. Sisäänkäynti, lattiat, sovituskopit, palvelutiskit ja muut asiakaspinnat tarvitsevat säännöllistä huolenpitoa etenkin vilkkaassa käytössä.</p><p>Siivous voidaan ajoittaa ennen avaamista, sulkemisen jälkeen tai soveltuvissa kohteissa myös päivän aikana.</p>', [('Asiakaspinnat kuntoon','Kiinnitämme huomion tiloihin, jotka muodostavat ensivaikutelman.'),('Aukioloihin sopiva rytmi','Siivous voidaan ajoittaa liiketoiminnan ympärille.'),('Sesonkijousto','Tarvetta voidaan kasvattaa kampanjoiden ja ruuhkahuippujen aikana.')], ['Sisäänkäynnit ja lattiat','Palvelu- ja kassatilat','Sovituskopit','Pöly- ja kosketuspinnat','Henkilöstötilat','WC-tilat','Roskien tyhjennys'], [('Milloin liiketilasiivous voidaan tehdä?','Tyypillisesti ennen avaamista tai sulkemisen jälkeen. Sopiva ajankohta määritellään kohteen mukaan.'),('Voiko siivousta lisätä sesonkiaikana?','Kyllä. Palvelurytmiä voidaan muuttaa esimerkiksi joulun, kampanjoiden tai tapahtumien ajaksi.'),('Teettekö myymälöiden ikkunoita?','Kyllä, ikkunoiden pesu voidaan sopia erilliseksi lisäpalveluksi.')], 'Liiketilasiivous Tampere'),
 'porrassiivous':('Porrassiivous Tampereella','Porrassiivous Tampereella taloyhtiöille ja kiinteistöille. Rappukäytävät, sisäänkäynnit ja yhteiset tilat sovitulla rytmillä.','Porrassiivous','<h2>Porraskäytävät ovat kiinteistön käyntikortti</h2><p>Säännöllinen porrassiivous vähentää irtolikaa, pitää sisäänkäynnit siistinä ja parantaa yhteisten tilojen viihtyisyyttä. Työrytmi voidaan painottaa vuodenajan mukaan.</p><p>Palvelu sopii taloyhtiöille, toimistokiinteistöille ja muille rakennuksille, joissa yhteisten kulkutilojen siisteys on tärkeää.</p>', [('Kausien mukaan','Syksy ja talvi voivat vaatia tiheämpää sisäänkäyntien huoltoa.'),('Selkeä kierros','Sovitut kerrokset ja yhteistilat käydään systemaattisesti läpi.'),('Lisätyöt helposti','Ikkunat, saunatilat tai varastojen yhteistilat voidaan sopia erikseen.')], ['Portaat ja tasanteet','Kaiteet ja kosketuspinnat','Sisäänkäynnit ja tuulikaapit','Hissin pinnat sovittaessa','Yhteiset käytävät','Roskien poisto sovitusti','Muut yhteiset tilat'], [('Kuinka usein rappukäytävä kannattaa siivota?','Rytmi riippuu asukasmäärästä, liikenteestä ja vuodenajasta. Monissa kohteissa 1–3 kertaa viikossa on sopiva lähtökohta.'),('Voiko talvella olla useampi siivouskerta?','Kyllä. Palvelua voidaan painottaa loska- ja hiekoituskaudelle.'),('Teettekö myös muita taloyhtiön tiloja?','Kyllä, sovittavia lisäkohteita voivat olla esimerkiksi yhteiset käytävät, sauna- ja kerhotilat sekä varastojen kulkualueet.')], 'Porrassiivous Tampere'),
 'ikkunanpesu':('Ikkunanpesu yrityksille Tampereella','Ikkunanpesu toimistoihin, liiketiloihin ja yrityksille Tampereella. Kausittainen tai kertaluonteinen palvelu muun siivouksen yhteydessä.','Ikkunanpesu','<h2>Puhtaat ikkunat viimeistelevät toimitilan</h2><p>Ikkunat vaikuttavat tilan valoisuuteen ja yleisilmeeseen. Yritysten ikkunanpesu voidaan tehdä kertaluonteisesti tai sovittuna kausityönä osana muuta siivouspalvelua.</p><p>Kohde arvioidaan ikkunoiden määrän, koon, saavutettavuuden ja pesutavan perusteella.</p>', [('Yrityskohteet','Toimistot, liiketilat ja muut soveltuvat toimitilat.'),('Kausipalvelu','Kevät- ja syyspesut voidaan aikatauluttaa etukäteen.'),('Yhdistettävissä','Ikkunanpesu voidaan liittää sopimussiivouksen lisätyöksi.')], ['Lasipintojen pesu sovitussa laajuudessa','Ikkunoiden sisä- ja ulkopinnat kohteen mukaan','Karmien ja puitteiden pyyhintä sovittaessa','Lasiseinät ja sisälasit','Liiketilan näkyvät lasipinnat','Kausittaiset pesut','Kohdekohtainen turvallisuusarvio'], [('Mitä yrityksen ikkunanpesu maksaa?','Hinta riippuu ikkunoiden määrästä, koosta, rakenteesta ja saavutettavuudesta. Pyydä kohdekohtainen tarjous.'),('Voiko ikkunanpesun yhdistää toimistosiivoukseen?','Kyllä. Se voidaan sopia esimerkiksi kevään ja syksyn jaksotyöksi.'),('Pesettekö myös sisäpuolisia lasiseiniä?','Kyllä, sisälasit ja lasiseinät voidaan sisällyttää palveluun.')], 'Ikkunanpesu Tampere'),
 'erikoissiivous':('Erikoissiivous Tampereella yrityksille','Erikoissiivous yrityksille Tampereella: tehostetut siivoukset, lattioiden peruspesut, tekstiilipinnat, yläpölyt ja muut kohdekohtaiset työt.','Erikoissiivous','<h2>Kun ylläpitosiivous ei yksin riitä</h2><p>Erikoissiivous täydentää säännöllistä ylläpitoa. Tarve voi syntyä kausittain, muutoksen yhteydessä tai silloin, kun tietyt pinnat tarvitsevat perusteellisemman käsittelyn.</p><p>Työmenetelmä valitaan pinnan, lian ja kohteen turvallisuusvaatimusten perusteella.</p>', [('Kohdekohtainen arvio','Valitsemme menetelmän materiaalien mukaan.'),('Sovittu rajaus','Työn sisältö ja laajuus määritellään tarjouksessa.'),('Osaksi vuosikelloa','Kausityöt voidaan aikatauluttaa etukäteen.')], ['Lattioiden peruspesut','Tekstiililattioiden ja kalusteiden puhdistus','Yläpölyjen poisto','Tehostetut pintapuhdistukset','Ikkunanpesut','Muuttojen yhteydessä tehtävät yrityssiivoukset','Muut erikseen sovittavat erikoistyöt'], [('Mitä erikoissiivous tarkoittaa?','Se tarkoittaa ylläpitosiivousta perusteellisempia tai erityismenetelmiä vaativia töitä, kuten lattioiden peruspesua tai tekstiilipintojen syväpuhdistusta.'),('Voiko erikoissiivouksen tilata kertaluonteisesti?','Kyllä. Palvelu voidaan tilata yksittäisenä työnä.'),('Voidaanko työt tehdä viikonloppuna?','Mahdollisuus sovitaan kohteen, työn laajuuden ja ajankohdan mukaan.')], 'Erikoissiivous Tampere'),
 'rakennussiivous':('Rakennussiivous Tampereella','Rakennussiivous Tampereella ja Pirkanmaalla. Rakentamisen aikainen siivous, loppusiivous ja työmaatilojen puhtaanapito sovitusti.','Rakennussiivous','<h2>Siisti työmaa tukee sujuvaa tekemistä</h2><p>Rakennussiivouksen tehtävä on hallita rakentamisen aikaista likaa, pölyä ja jätteitä sekä valmistella tiloja seuraaviin työvaiheisiin. Tarjoamme kohdekohtaisesti rakentamisen aikaista siivousta ja loppusiivousta.</p><p>Työ sovitetaan työmaan vaiheeseen, turvallisuusohjeisiin ja aikatauluun.</p>', [('Vaiheiden mukaan','Siivous sovitetaan työmaan etenemiseen.'),('Turvallinen toteutus','Kohteen perehdytys ja työmaakohtaiset vaatimukset huomioidaan.'),('Loppusiivous','Tilat valmistellaan sovitulle puhtaustasolle ennen käyttöönottoa.')], ['Rakentamisen aikainen pöly- ja irtolian poisto','Työalueiden siistiminen','Jätteiden keräys ja sovittu lajittelu','Työmaatilojen siivous','Loppusiivous','Ikkunoiden pesu sovittaessa','Muut työvaihekohtaiset tehtävät'], [('Mitä rakennussiivous sisältää?','Sisältö riippuu työmaan vaiheesta. Se voi sisältää rakentamisen aikaista puhtaanapitoa, työmaatilojen siivousta ja loppusiivousta.'),('Teettekö loppusiivouksia?','Kyllä, loppusiivous voidaan toteuttaa kohteen vaatimustason ja aikataulun mukaan.'),('Palveletteko Tampereen lisäksi Pirkanmaalla?','Kyllä, kohteita voidaan toteuttaa Tampereella ja sovitusti muualla Pirkanmaalla.')], 'Rakennussiivous Tampere'),
 'muuttosiivous':('Muuttosiivous Tampereella yrityksille ja koteihin','Muuttosiivous Tampereella yritysten toimitiloihin ja koteihin. Huolellinen loppusiivous muuton yhteydessä. Pyydä tarjous.','Muuttosiivous','<h2>Muuttosiivous vanhaan tai uuteen tilaan</h2><p>Muutossa siivouksen pitää osua oikeaan hetkeen. Teemme muuttosiivouksia erityisesti yritysten toimitiloihin sekä erikseen sovittaessa koteihin Tampereella.</p><p>Laajuus määritellään tilan koon, kunnon ja luovutusvaatimusten mukaan.</p>', [('Aikataulutettu','Siivous sovitetaan muuttopäivään ja avainten luovutukseen.'),('Laaja loppusiivous','Työ voidaan mitoittaa tyhjän tilan perusteelliseen puhdistukseen.'),('Lisäpalvelut','Ikkunat ja muut erikseen sovitut työt voidaan liittää mukaan.')], ['Lattiat ja listat','Kaappien ulko- ja sisäpinnat sovittaessa','Keittiön pinnat ja kodinkoneiden ulkopinnat','WC- ja pesutilat','Ovet ja kosketuspinnat','Tyhjät työ- tai asuintilat','Ikkunanpesu erikseen sovittaessa'], [('Miten muuttosiivous hinnoitellaan?','Hinta riippuu pinta-alasta, tilan kunnosta, kalusteiden määrästä ja sovitusta laajuudesta.'),('Voiko siivouksen tehdä avainten luovutuspäivänä?','Usein kyllä, jos aikataulusta sovitaan riittävän ajoissa.'),('Teettekö yritysten toimitilojen muuttosiivouksia?','Kyllä. Yritysmuuttojen yhteydessä voimme siivota vanhan tai uuden toimitilan sovitun laajuuden mukaan.')], 'Muuttosiivous Tampere')
}
for slug,(h1,desc,crumb,intro,features,includes,faq,kw) in services.items():
    b=service_body(h1,desc,crumb,intro,features,includes,faq,kw)
    title=f'{h1} | TampereSiivous'
    pages[f'{slug}/index.html']=page(title,desc,slug,b,faq)

# Service hub
cards=[('Toimistosiivous','/toimistosiivous/','Toimistojen säännöllinen ylläpitosiivous.'),('Yrityssiivous','/yrityssiivous/','Siivous eri kokoisille yrityksille ja työympäristöille.'),('Sopimussiivous','/sopimussiivous/','Toistuva palvelu sovitulla työohjeella.'),('Toimitilasiivous','/toimitilasiivous/','Toimistot, työtilat, varastot ja sosiaalitilat.'),('Liiketilasiivous','/liiketilasiivous/','Myymälät, showroomit ja asiakastilat.'),('Porrassiivous','/porrassiivous/','Taloyhtiöiden ja kiinteistöjen yhteiset tilat.'),('Ikkunanpesu','/ikkunanpesu/','Yritysten ikkunat ja lasipinnat.'),('Erikoissiivous','/erikoissiivous/','Peruspesut ja tehostetut puhdistukset.'),('Rakennussiivous','/rakennussiivous/','Rakentamisen aikainen ja loppusiivous.'),('Muuttosiivous','/muuttosiivous/','Muuttoon ajoitettu perusteellinen siivous.')]
body=hero('Siivouspalvelut Tampereella','Siivouspalvelut yrityksille, toimitiloille ja kiinteistöille Tampereella ja Pirkanmaalla.','Palvelut','Siivouspalvelu Tampere')+'''<main><section><div class="container"><div class="section-head"><h2>Valitse tarpeeseesi sopiva palvelu</h2><p>Erityinen painopisteemme on toimisto- ja yrityssiivouksessa, mutta saman kumppanin kautta saat myös lisä- ja kausityöt.</p></div><div class="grid">'''+''.join(f'<a class="service-card" href="{u}"><h3>{n}</h3><p>{d}</p><span class="more">Tutustu →</span></a>' for n,u,d in cards)+'''</div></div></section></main>'''
pages['palvelut/index.html']=page('Siivouspalvelu Tampere | Palvelut yrityksille | TampereSiivous','Siivouspalvelut Tampereella yrityksille: toimistosiivous, sopimussiivous, toimitilasiivous, liiketilasiivous, porrassiivous ja erikoissiivous.','palvelut',body)

# Pricing
faq=[('Miksi sopimussiivouksella ei ole yhtä tuntihintaa?','Säännöllisessä yrityssiivouksessa olennaista on kohteen työmäärä, rytmi ja palvelutaso. Kohdekohtainen hinta on yleensä tarkempi kuin geneerinen tuntihinta.'),('Onko tarjous maksullinen?','Ei. Tarjouspyyntö ja alustava palvelukartoitus ovat maksuttomia.'),('Sisältyykö arvonlisävero hintaan?','Yritysasiakkaiden tarjoukset eritellään selkeästi niin, että veroton hinta ja arvonlisävero näkyvät tarjouksessa.')]
body=hero('Siivouksen hinnasto yrityksille','Yrityssiivouksen hinta muodostuu kohteen koosta, käyttöasteesta, siivoustiheydestä ja sovituista tehtävistä.','Hinnasto','Yrityssiivous hinta Tampere')+'''<main><section><div class="container"><div class="section-head"><h2>Selkeä hinta alkaa oikeasta mitoituksesta</h2><p>Emme halua luvata yhtä hintaa kaikkiin kohteisiin, koska 100 m² hiljainen toimisto ja 100 m² vilkas asiakastila eivät vaadi samaa työmäärää.</p></div><div class="grid"><div class="price-card"><span class="eyebrow">Sopimussiivous</span><h3>Toimistot ja yritykset</h3><strong>Tarjouksen mukaan</strong><p>Säännöllinen palvelu, jonka hinta perustuu sovittuun työmäärään ja rytmiin.</p></div><div class="price-card"><span class="eyebrow">Kertasiivous</span><h3>Yritysten yksittäiset työt</h3><strong>Kohdekohtainen</strong><p>Sopii esimerkiksi tehosiivoukseen, muuttoon tai kertaluonteiseen tarpeeseen.</p></div><div class="price-card"><span class="eyebrow">Lisätyöt</span><h3>Ikkunat ja erikoistyöt</h3><strong>Erillinen arvio</strong><p>Hinnoittelu riippuu pinta-alasta, menetelmistä ja saavutettavuudesta.</p></div></div></div></section>'''+faq_html(faq)+'''</main>'''
pages['hinnasto/index.html']=page('Yrityssiivous hinta Tampere | Siivouksen hinnasto | TampereSiivous','Mitä yrityssiivous maksaa Tampereella? Katso miten toimisto- ja sopimussiivouksen hinta muodostuu ja pyydä maksuton tarjous.','hinnasto',body,faq)

# Company
body=hero('Paikallinen siivouskumppani Tampereella','TampereSiivous keskittyy erityisesti toimistojen, yritysten ja toimitilojen siivoukseen Tampereella ja Pirkanmaalla.','Yritys','Siivousyritys Tampere')+f'''<main><section><div class="container split"><div class="content"><h2>Yrityssiivousta käytännöllisesti</h2><p>Tavoitteemme on tehdä siivouspalvelusta mahdollisimman helppo ostaa ja hallita. Palvelu suunnitellaan sen mukaan, miten tilaa oikeasti käytetään.</p><p>TampereSiivous toimii Tyozyn siivouspalvelubrändinä. Palvelussa korostuvat paikallisuus, nopea yhteydenpito, selkeät tarjoukset ja joustavat ratkaisut.</p><h3>Y-tunnus</h3><p>{BID}</p></div><div class="cta"><h2>Miksi yritysasiakkaat valitsevat paikallisen kumppanin?</h2><p>Kun yhteydenpito on suoraa ja päätökset tehdään lähellä, muutoksiin on helpompi reagoida.</p><a class="btn primary" href="/ota-yhteytta/">Ota yhteyttä</a></div></div></section></main>'''
pages['yritys/index.html']=page('Siivousyritys Tampere | TampereSiivous','Paikallinen siivousyritys Tampereella yrityksille, toimistoille ja toimitiloille. Tutustu TampereSiivoukseen ja pyydä tarjous.','yritys',body)

# areas
areas=['Tampere keskusta','Hervanta','Kaleva','Tammela','Hatanpää','Nekala','Lielahti','Linnainmaa','Vuores','Pirkkala','Nokia','Ylöjärvi','Kangasala','Lempäälä']
body=hero('Siivouspalvelu Tampereella ja Pirkanmaalla','Palvelemme yrityksiä Tampereen eri kaupunginosissa sekä sovitusti lähikunnissa.','Palvelualueet','Siivouspalvelu Tampere')+'''<main><section><div class="container"><div class="section-head"><h2>Palvelualueemme</h2><p>Erityisesti toimistosiivous, yrityssiivous ja sopimussiivous voidaan toteuttaa seuraavilla alueilla.</p></div><div class="grid">'''+''.join(f'<div class="service-card"><h3>Siivous {a}</h3><p>Toimisto- ja yrityssiivous alueella {a}. Kysy saatavuus ja tarjous.</p></div>' for a in areas)+'''</div></div></section></main>'''
pages['alueet/index.html']=page('Siivouspalvelu Tampere ja Pirkanmaa | Palvelualueet','Toimisto- ja yrityssiivous Tampereella, Hervannassa, Hatanpäällä, Kalevassa, Pirkkalassa, Nokialla, Ylöjärvellä, Kangasalla ja Lempäälässä.','alueet',body)

# Quote / contact
form=f'''<form><div class="grid formgrid"><label>Nimi<input required name="name"></label><label>Yritys<input name="company"></label></div><div class="grid formgrid"><label>Sähköposti<input required type="email" name="email"></label><label>Puhelin<input name="phone"></label></div><div class="grid formgrid"><label>Palvelu<select><option>Toimistosiivous</option><option>Yrityssiivous</option><option>Sopimussiivous</option><option>Toimitilasiivous</option><option>Ikkunanpesu</option><option>Muu</option></select></label><label>Siivoustiheys<select><option>1x viikossa</option><option>2–3x viikossa</option><option>4–5x viikossa</option><option>Kertasiivous</option><option>En tiedä vielä</option></select></label></div><label>Kerro kohteesta<textarea placeholder="Esim. toimisto 250 m², 20 työntekijää, 3 wc:tä, siivous toivotusti 3 kertaa viikossa..."></textarea></label><button class="btn primary" type="submit">Lähetä tarjouspyyntö</button></form>'''
body=hero('Pyydä tarjous toimisto- tai yrityssiivouksesta','Kerro muutama tieto kohteesta. Teemme tarpeeseenne sopivan ehdotuksen siivouksen sisällöstä ja rytmistä.','Pyydä tarjous','Siivoustarjous Tampere')+f'''<main><section><div class="container split"><div>{form}</div><div class="contact-card"><h2>Nopea yhteys</h2><p><strong>Puhelin</strong><br><a href="tel:{PHONE_LINK}">{PHONE}</a></p><p><strong>Sähköposti</strong><br><a href="mailto:{EMAIL}">{EMAIL}</a></p><p><strong>Palvelualue</strong><br>Tampere ja Pirkanmaa</p><p><strong>Y-tunnus</strong><br>{BID}</p></div></div></section></main>'''
pages['pyyda-tarjous/index.html']=page('Pyydä tarjous | Toimistosiivous Tampere | TampereSiivous','Pyydä maksuton tarjous toimistosiivouksesta, yrityssiivouksesta tai sopimussiivouksesta Tampereella.','pyyda-tarjous',body)
body=hero('Ota yhteyttä','Ota yhteyttä TampereSiivoukseen, kun tarvitset toimisto-, yritys- tai toimitilasiivousta Tampereella.','Ota yhteyttä','Siivouspalvelu Tampere yhteystiedot')+f'''<main><section><div class="container grid"><div class="contact-card"><h3>Puhelin</h3><p><a href="tel:{PHONE_LINK}">{PHONE}</a></p></div><div class="contact-card"><h3>Sähköposti</h3><p><a href="mailto:{EMAIL}">{EMAIL}</a></p></div><div class="contact-card"><h3>Yritystiedot</h3><p>TampereSiivous / Tyozy<br>Y-tunnus {BID}<br>Tampere, Finland</p></div></div></section><section class="band"><div class="container"><div class="section-head"><h2>Lähetä viesti</h2></div>{form}</div></section></main>'''
pages['ota-yhteytta/index.html']=page('Ota yhteyttä | TampereSiivous','TampereSiivous yhteystiedot. Ota yhteyttä toimisto- ja yrityssiivouksesta Tampereella.','ota-yhteytta',body)

# SEO content/blog
articles=[
('kuinka-usein-toimisto-kannattaa-siivota','Kuinka usein toimisto kannattaa siivota?','Toimiston sopiva siivoustiheys riippuu käyttöasteesta, henkilöstömäärästä ja tilatyypeistä. Katso käytännöllinen opas Tampereen yrityksille.','Toimiston siivoustiheys ei ole pelkkä neliökysymys. Vilkas wc-tila tai henkilöstökeittiö voi vaatia päivittäistä huoltoa, vaikka työpistealueet pärjäisivät harvemmalla rytmillä. Hyvä lähtökohta on jakaa toimisto vyöhykkeisiin: korkean käyttöasteen tilat, normaalin käyttöasteen tilat ja harvemmin käytetyt tilat. Näin siivousta voidaan kohdistaa tehokkaammin.','toimistosiivous Tampere'),
('yrityssiivouksen-hinta','Mistä yrityssiivouksen hinta muodostuu?','Yrityssiivouksen hintaan vaikuttavat muutkin asiat kuin neliöt. Lue mitkä tekijät ratkaisevat toimisto- ja sopimussiivouksen hinnan.','Yrityssiivouksen hintaa arvioitaessa tarkastellaan pinta-alan lisäksi tilojen käyttötapaa, kalustusta, henkilöstömäärää, saniteettitilojen määrää, siivoustiheyttä, kulkuyhteyksiä ja toivottua laatutasoa. Säännöllisessä siivouksessa hyvin tehty mitoitus auttaa välttämään sekä aliresursointia että turhaa työtä.','yrityssiivous hinta Tampere'),
('toimistosiivouksen-tarkistuslista','Toimistosiivouksen tarkistuslista yritykselle','Mitä hyvään toimistosiivoukseen kuuluu? Käytännöllinen tarkistuslista työpisteisiin, neuvottelutiloihin, keittiöön ja wc-tiloihin.','Toimistosiivouksen työohje kannattaa jakaa käyntikohtaisiin tehtäviin ja harvemmin tehtäviin jaksotöihin. Jokaisella käynnillä huomiota saavat yleensä roskat, lattiat, wc-tilat, keittiö ja näkyvät kosketuspinnat. Harvemmin tehtäviä töitä voivat olla yläpölyt, lasipinnat ja lattioiden perusteellisempi hoito.','toimistosiivous tarkistuslista')]
for slug,h1,desc,text,kw in articles:
    body=hero(h1,desc,'Oppaat',kw)+f'''<main><section><div class="container content"><p>{text}</p><h2>Käytännöllinen tapa suunnitella siivous</h2><p>Kirjaa ensin tilat, niiden käyttöaste ja tärkeimmät laatukriteerit. Sen jälkeen tehtävät voidaan jakaa päivittäisiin, viikoittaisiin ja kausittaisiin töihin. Tämä tekee palvelusta läpinäkyvän ja helpottaa myös hinnan arviointia.</p><h2>Pyydä kohdekohtainen arvio</h2><p>Jos et ole varma oikeasta rytmistä, pyydä kartoitus. <a style="color:var(--brand);font-weight:800" href="/pyyda-tarjous/">TampereSiivous tekee yrityksellesi ehdotuksen →</a></p></div></section></main>'''
    pages[f'oppaat/{slug}/index.html']=page(f'{h1} | TampereSiivous',desc,f'oppaat/{slug}',body)

# legal
body=hero('Tietosuojaseloste','TampereSiivous käsittelee yhteydenottojen ja tarjouspyyntöjen tietoja vain asiakaspalvelun, tarjousten ja sopimusasioiden hoitamiseen.','Tietosuoja','Tietosuoja')+'''<main><section><div class="container content"><h2>Rekisterinpitäjä</h2><p>Tyozy / TampereSiivous, Y-tunnus 3549202-5.</p><h2>Käsiteltävät tiedot</h2><p>Yhteydenottoihin liittyvät nimi-, yritys-, yhteys- ja kohdetiedot sekä viestin sisältö.</p><h2>Käsittelyn tarkoitus</h2><p>Tarjouspyyntöihin vastaaminen, asiakassuhteen hoitaminen, laskutus ja lakisääteiset velvoitteet.</p><h2>Oikeutesi</h2><p>Voit pyytää sinua koskevien tietojen tarkastamista tai korjaamista ottamalla yhteyttä rekisterinpitäjään.</p></div></section></main>'''
pages['tietosuoja/index.html']=page('Tietosuojaseloste | TampereSiivous','TampereSiivous tietosuojaseloste.','tietosuoja',body)
body=hero('Saavutettavuus','Pyrimme siihen, että tamperesiivous.com on selkeä, luettava ja käytettävissä eri laitteilla.','Saavutettavuus','Saavutettavuus')+'''<main><section><div class="container content"><h2>Saavutettavuuden tavoite</h2><p>Sivusto on suunniteltu responsiiviseksi, näppäimistöllä käytettäväksi ja riittävän selkeällä kontrastilla. Jos huomaat saavutettavuusongelman, ota yhteyttä sähköpostitse.</p></div></section></main>'''
pages['saavutettavuus/index.html']=page('Saavutettavuus | TampereSiivous','TampereSiivous sivuston saavutettavuustiedot.','saavutettavuus',body)

for rel,html in pages.items():
    p=root/rel; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(html,encoding='utf-8')

# sitemap and robots
urls=[]
for rel in pages:
    if rel=='index.html': u=DOMAIN+'/'
    else: u=DOMAIN+'/'+rel.replace('index.html','')
    urls.append(u)
(root/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'<url><loc>{u}</loc><changefreq>{"weekly" if "/oppaat/" in u else "monthly"}</changefreq><priority>{"1.0" if u==DOMAIN+"/" else "0.8"}</priority></url>' for u in urls)+'\n</urlset>',encoding='utf-8')
(root/'robots.txt').write_text(f'User-agent: *\nAllow: /\nSitemap: {DOMAIN}/sitemap.xml\n',encoding='utf-8')
(root/'404.html').write_text(page('Sivua ei löytynyt | TampereSiivous','Sivua ei löytynyt.','404','<main>'+hero('Sivua ei löytynyt','Tarkista osoite tai palaa etusivulle.','404')+'<section><div class="container"><a class="btn primary" href="/">Etusivulle</a></div></section></main>'),encoding='utf-8')
print(f'Generated {len(pages)} SEO pages')
